### ISSUE TITLE
Usability overview

### ISSUE THREAD

**Issue by StenGruener** [mnestix/mnestix-browser#18]
Hi team, great work you have done.

On the overview page (list of aas) it is quite counter-intutive that clicking on the picture will open the aas.

Proposal would be to make hover on the whole table row and move on to the aas when user klicks anywhere in the row.

BR
Sten
![image](https://github.com/mnestix/mnestix-browser/assets/69786685/39133b11-72ad-4df5-b746-7292209d1468)

**Comment by NilsXitaso** [comment]
Hello Sten,
thanks for your UX review and your feedback we will include this in further UX discussions and fix your request.

Greetings,
Nils

**Comment by hofermo** [comment]
@StenGruener 
We implemented some improvements to the AAS List, stay tuned for our next release to test them out :)

Here are some screenshots:
![image](https://github.com/user-attachments/assets/295fed95-f1c5-4d19-aa61-8d5f7f7df949)
![image](https://github.com/user-attachments/assets/d7f47fe7-be36-470c-9200-3c0785e133a2)

**Comment by StenGruener** [comment]
👍
