### ISSUE TITLE
Missing scanning feature

### ISSUE THREAD

**Issue by jomo02** [mnestix/mnestix-browser#34]
Hi,

it seems that the QR code scanner feature is just displayed, but not working yet.
Do you plan to integrate it in the near future?
The easiest way could be to use a third-party library like this one (it uses the [Barcode Detection API](https://developer.mozilla.org/en-US/docs/Web/API/Barcode_Detection_API)):
https://github.com/nimiq/qr-scanner/tree/master

**Comment by hofermo** [comment]
Thank you for your issue!
We also feel that this would be an important addition to Mnestix Browser :+1: 
It sits currently at the top of our backlog and will be included in the next few weeks.
I will send you an update if it is ready to test out from the dev branch.

**Comment by hofermo** [comment]
Dear @jomo02,
as shown today in our Open Hour you can now test the QR Scanner on the dev branch and it will be included in our next release.
If you have any questions or feedback feel free to write them here or close the issue if you are satisfied 😃 

Also if you have any other remarks or features you would like to see in Mnestix Browser feel free to add another issue 👍

**Comment by hofermo** [comment]
Dear @jomo02,
We just released the scanning feature in version 1.2.0.
Please check it out: https://github.com/mnestix/mnestix-browser/releases/tag/release%2Fmnestix-browser-v1.2.0
I will close this issue, but if you have any complains, feel free to reopen it or open another one.
